import test from "node:test"
import assert from "node:assert/strict"
import {ADMIN_COMMANDS, CommandKind, MAINTENANCE_COMMANDS, parseCommand, parseGroupCommand, resolveClassCommand, resolveSection, suggestCommand} from "../../src/domain/Command.js"

test("parses slash and plain commands with aliases", () => {
  assert.deepEqual(parseCommand("/list"), {kind: CommandKind.LIST, argument: ""})
  assert.deepEqual(parseCommand("files *.pdf"), {kind: CommandKind.FILES, argument: "*.pdf"})
  assert.deepEqual(parseCommand("/отменить"), {kind: CommandKind.DROP, argument: ""}, "drops a preview; never a class cancellation")
  assert.deepEqual(parseCommand("  /GET  my report.pdf "), {kind: CommandKind.GET, argument: "my report.pdf"})
  assert.deepEqual(parseCommand("/help"), {kind: CommandKind.HELP, argument: ""})
  assert.deepEqual(parseCommand("/?"), {kind: CommandKind.HELP, argument: ""}, "the help is shown as ? everywhere")
  assert.deepEqual(parseCommand("/??"), {kind: CommandKind.HELP, argument: "all"}, "?? = all commands")
  assert.deepEqual(parseCommand("??"), {kind: CommandKind.HELP, argument: "all"}, "the slash is optional")
  assert.deepEqual(parseCommand("/помощь"), {kind: CommandKind.HELP, argument: ""}, "the words keep working, they are just not advertised")
  assert.equal(suggestCommand("/??"), null, "? and ?? are the help, not a typo")
  assert.equal(suggestCommand("/помош"), "/?", "hints name the help as ?")
  assert.deepEqual(parseCommand("hello there"), {kind: CommandKind.UNKNOWN, argument: "there"})
  assert.deepEqual(parseCommand(""), {kind: CommandKind.UNKNOWN, argument: ""})
  assert.deepEqual(parseCommand("/last 06.10"), {kind: CommandKind.LAST, argument: "06.10"})
  assert.deepEqual(parseCommand("Прошлое"), {kind: CommandKind.LAST, argument: ""})
  assert.deepEqual(parseCommand("/перенос 23.09 20:00"), {kind: CommandKind.MOVE, argument: "23.09 20:00"})
  assert.deepEqual(parseCommand("/cancel"), {kind: CommandKind.CANCEL, argument: ""})
  assert.deepEqual(parseCommand("отмена 23.09"), {kind: CommandKind.CANCEL, argument: "23.09"})
})

test("in the group only a slash (or the Latin word prius) makes a command: sentences starting with a command word are talk", () => {
  const kinds = (texts) => texts.map((t) => parseGroupCommand(t).kind)
  assert.deepEqual(kinds(["Занятие переносится на вторник", "занятие", "Расписание не поменялось?", "Спиноза писал о свободе", "spinoza said", "Class was great", "Прошлое занятие было длинным", "задание на неделю", "Список литературы:", "дай подумать", "статус кво", "help me"]), Array(12).fill(CommandKind.UNKNOWN))
  assert.deepEqual(kinds(["/занятие", "/Занятие 19.09 Тема", "/расписание", "/spinoza", "/Spinoza расписание", "/список", "/статус", "/?"]), [CommandKind.SESSION, CommandKind.SESSION, CommandKind.SCHEDULE, CommandKind.SPINOZA, CommandKind.SCHEDULE, CommandKind.LIST, CommandKind.STATUS, CommandKind.HELP])
  assert.deepEqual(parseGroupCommand("prius 05.09"), {kind: CommandKind.LAST, argument: "05.09", words: 1}, "prius needs no slash")
  assert.deepEqual(parseGroupCommand("Prius"), {kind: CommandKind.LAST, argument: "", words: 1})
  assert.equal(parseGroupCommand("last").kind, CommandKind.UNKNOWN, "the English alias needs the slash")
  assert.equal(parseGroupCommand("/last").kind, CommandKind.LAST)
  assert.equal(parseCommand("занятие").kind, CommandKind.SESSION, "privately the plain word still works")
})

test("the Latin words and /spinoza subcommands of the group", () => {
  assert.deepEqual(parseCommand("prius 08.09"), {kind: CommandKind.LAST, argument: "08.09"})
  assert.deepEqual(parseGroupCommand("/spinoza занятие 14.09 Тема"), {kind: CommandKind.SESSION, argument: "14.09 Тема", words: 2})
  assert.deepEqual(parseGroupCommand("/spinoza class"), {kind: CommandKind.SESSION, argument: "", words: 2})
  assert.deepEqual(parseGroupCommand("/spinoza расписание"), {kind: CommandKind.SCHEDULE, argument: "", words: 2})
  assert.deepEqual(parseGroupCommand("/spinoza prius 08.09"), {kind: CommandKind.LAST, argument: "08.09", words: 2})
  assert.deepEqual(parseGroupCommand("/spinoza перенос 23.09 20:00"), {kind: CommandKind.SPINOZA, argument: "перенос 23.09 20:00", words: 1}, "moving is a private command")
  assert.deepEqual(parseGroupCommand("/spinoza отмена"), {kind: CommandKind.SPINOZA, argument: "отмена", words: 1})
  assert.deepEqual(parseGroupCommand("/spinoza"), {kind: CommandKind.SPINOZA, argument: "", words: 1})
  assert.deepEqual(parseGroupCommand("/spinoza all"), {kind: CommandKind.SPINOZA, argument: "all", words: 1})
  assert.deepEqual(parseGroupCommand("/class Тема"), {kind: CommandKind.SESSION, argument: "Тема", words: 1}, "the direct command still works")
  assert.deepEqual(parseGroupCommand("conatus"), {kind: CommandKind.UNKNOWN, argument: "", words: 1}, "the trigger word is not a command")
  assert.deepEqual(parseCommand("/сп *.pdf"), {kind: CommandKind.LIST, argument: "*.pdf"})
  assert.deepEqual(parseCommand("/ув вкл"), {kind: CommandKind.WATCH, argument: "вкл"})
  assert.deepEqual(parseCommand("/э Э1т7"), {kind: CommandKind.ETHICS, argument: "Э1т7"})
  assert.deepEqual(parseCommand("/гол Когда? | Пн | Вт"), {kind: CommandKind.VOTE, argument: "Когда? | Пн | Вт"})
  assert.deepEqual(parseCommand("/poll"), {kind: CommandKind.VOTE, argument: ""})
})

test("suggestCommand finds the nearest private command for a typo or a prefix", () => {
  assert.equal(suggestCommand("/gett"), "/дай <номер|имя>")
  assert.equal(suggestCommand("/списк"), "/список [шаблон]")
  assert.equal(suggestCommand("/расписани"), "/занятие расписание [день] [время]")
  assert.equal(suggestCommand("/уведомлени"), "/уведомления [вкл|выкл]")
  assert.equal(suggestCommand("/xyzq"), null)
  assert.equal(suggestCommand("/invit"), null, "hidden admin commands are never suggested")
  assert.equal(suggestCommand("/админ"), null, "admin commands are never suggested to users (/админы, /разадмин)")
  assert.equal(suggestCommand("/разадми"), null)
})

test("admin-only commands and member maintenance commands are disjoint sets", () => {
  assert.deepEqual([...ADMIN_COMMANDS].sort(), ["admin", "admins", "invite", "join", "unadmin"])
  assert.deepEqual([...MAINTENANCE_COMMANDS].sort(), ["delete", "deleted", "restore", "space", "status"])
  for (const kind of MAINTENANCE_COMMANDS) assert.equal(ADMIN_COMMANDS.has(kind), false)
})

test("the private /занятие section resolves to its operations; anything else is a date for the card", () => {
  const r = (text) => resolveClassCommand(parseCommand(text))
  assert.deepEqual(r("/занятие"), {kind: CommandKind.HOMEWORK, argument: ""})
  assert.deepEqual(r("/занятие 19.09"), {kind: CommandKind.HOMEWORK, argument: "19.09"})
  assert.deepEqual(r("/з завтра"), {kind: CommandKind.HOMEWORK, argument: "завтра"})
  assert.deepEqual(r("/занятие список 09.2026"), {kind: CommandKind.SESSIONS, argument: "09.2026"})
  assert.deepEqual(r("/з с архив"), {kind: CommandKind.SESSIONS, argument: "архив"})
  assert.deepEqual(r("/занятие расписание сб 12:15"), {kind: CommandKind.SCHEDULE, argument: "сб 12:15"})
  assert.deepEqual(r("/з р"), {kind: CommandKind.SCHEDULE, argument: ""})
  assert.deepEqual(r("/занятие перенос 23.09 20:00"), {kind: CommandKind.MOVE, argument: "23.09 20:00"})
  assert.deepEqual(r("/з п 20:00"), {kind: CommandKind.MOVE, argument: "20:00"})
  assert.deepEqual(r("/занятие отмена 23.09"), {kind: CommandKind.CANCEL, argument: "23.09"})
  assert.deepEqual(r("/занятие отменить"), {kind: CommandKind.DROP, argument: ""}, "отменить = drop the preview, отмена = cancel a class")
  assert.deepEqual(r("/з о"), {kind: CommandKind.CANCEL, argument: ""})
  assert.deepEqual(r("/занятие подтвердить"), {kind: CommandKind.CONFIRM, argument: ""})
  assert.deepEqual(r("/занятие ?"), {kind: CommandKind.CLASS_HELP, argument: ""})
  assert.deepEqual(r("/дз 19.09"), {kind: CommandKind.HOMEWORK, argument: "19.09"}, "the old commands are untouched")
  assert.deepEqual(r("/занятия 2026"), {kind: CommandKind.SESSIONS, argument: "2026"})
  assert.deepEqual(r("/расписание"), {kind: CommandKind.SCHEDULE, argument: ""})
  assert.equal(suggestCommand("/заняти"), "/занятие [дата]")
})

test("the private /файлы section resolves like /занятие; anything else is a pattern for the list", () => {
  const r = (text) => resolveSection(parseCommand(text))
  assert.deepEqual(r("/файлы"), {kind: CommandKind.LIST, argument: ""})
  assert.deepEqual(r("/файлы *.pdf"), {kind: CommandKind.LIST, argument: "*.pdf"})
  assert.deepEqual(r("/ф с *.pdf"), {kind: CommandKind.LIST, argument: "*.pdf"})
  assert.deepEqual(r("/файлы дай 3"), {kind: CommandKind.GET, argument: "3"})
  assert.deepEqual(r("/ф д 3"), {kind: CommandKind.GET, argument: "3"})
  assert.deepEqual(r("/файлы удалить 2"), {kind: CommandKind.DELETE, argument: "2"})
  assert.deepEqual(r("/ф к"), {kind: CommandKind.DELETED, argument: ""})
  assert.deepEqual(r("/файлы восстановить 1"), {kind: CommandKind.RESTORE, argument: "1"})
  assert.deepEqual(r("/ф м"), {kind: CommandKind.SPACE, argument: ""})
  assert.deepEqual(r("/файлы ?"), {kind: CommandKind.FILES_HELP, argument: ""})
  assert.deepEqual(r("/files ?"), {kind: CommandKind.FILES_HELP, argument: ""})
  assert.deepEqual(r("/список *.pdf"), {kind: CommandKind.LIST, argument: "*.pdf"}, "the old commands are untouched")
  assert.deepEqual(r("/дай 3"), {kind: CommandKind.GET, argument: "3"})
  assert.equal(suggestCommand("/фай"), "/файлы [шаблон]")
})

test("every section and frequent action has a one-letter form; one-letter aliases never feed the typo hints", () => {
  const r = (text) => resolveSection(parseCommand(text))
  assert.deepEqual(r("/д 3"), {kind: CommandKind.GET, argument: "3"})
  assert.deepEqual(r("/г з 1"), {kind: CommandKind.VOTE, argument: "з 1"})
  assert.deepEqual(r("/у вкл"), {kind: CommandKind.WATCH, argument: "вкл"})
  assert.deepEqual(r("/с"), {kind: CommandKind.STATUS, argument: ""})
  assert.deepEqual(r("/п"), {kind: CommandKind.CONFIRM, argument: ""})
  assert.deepEqual(r("/о"), {kind: CommandKind.DROP, argument: ""})
  assert.deepEqual(r("/?"), {kind: CommandKind.HELP, argument: ""})
  assert.deepEqual(r("? все"), {kind: CommandKind.HELP, argument: "все"})
  assert.deepEqual(r("/з о 23.09"), {kind: CommandKind.CANCEL, argument: "23.09"})
  assert.equal(suggestCommand("/x"), null)
  assert.equal(suggestCommand("/дa"), "/занятие [дата]", "a two-letter typo still gets a word command, never a letter")
})
